schema_version: 1

context:
  name: qwen-vl-utils
  version: 0.0.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/qwen_vl_utils-${{ version }}.tar.gz
  sha256: e5bb985508a85dfc339989870a35fbd0362f96bbb01e7e0472ff89942d33ceb8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - pillow
    - av
    - packaging
    # Undeclared upstream depedencies on pytorch
    - pytorch
    - torchvision

tests:
  - python:
      imports:
        - qwen_vl_utils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/QwenLM/Qwen2.5-VL/
  summary: Qwen Vision Language Model Utils - PyTorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zbowling
